baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "US Cyber Response Blog"
theme = "PaperMod"

# Set default theme to light mode
[params]
  description = "Insights on cybersecurity, technology policy, and national security"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "light"
  disableThemeToggle = false  # Set to true if you want to remove the theme toggle completely
  
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
